development:
  SECRET_KEY_BASE: 'development key here '
  CALENDAR_CLIENT_ID: '982321280742-in60eh1a53cgknc3p8sv4f2cfmdkvngg.apps.googleusercontent.com'
  CALENDAR_SECRET_ID: 'p1k1eAtRxpfefGSJ3R2MSzkc'
  CALENDAR_ID: 'myopustime@gmail.com'
#  CALENDAR_CLIENT_ID: '444748116899-m7hi657r7l9jq68qgbg9d9evft0cpbca.apps.googleusercontent.com'  #dhimananuj93@gmail.com
#  CALENDAR_SECRET_ID: 'laFEhH-0z7yF4-0LkRXOXuAC'
#  CALENDAR_ID: 'dhimananuj93@gmail.com'
  XERO_KEY: 'CPYUMXYGRAIKEHPEGBLLX0OVLPNK4C'
  XERO_SECRET: 'QY0RGYEYNMRCKIGVGRXUQYAP6NCONF'
  FB_KEY: '439980326202518'                         # testing.slinfy01@gmail.com  - slinfy007
  FB_SECRET: 'd02bd613ff779e0d5929ec036c88becb'
  ONLINE_FB_KEY: '1379043992119808'
  ONLINE_FB_SECRET: 'bf83dec4dd5e27075c2a97d3c93ed7e5'
  plivo_access_id: 'MAM2Y1NTE4ZJUWYTUXZT'
  plivo_secret_id: 'MzNjNTJlMTgwMWZiMWU2ODE4MzA5MWZiNjIwZTJk'
  # Quickbooks Credentials
  #-------------------------------------------------#

  #-------------------------------------------------#

   # Authorized.net Credentials
  #-------------------------------------------------#

  #-------------------------------------------------#
  elev_api_key: "57bcf30f63ed1"
  send_grid_user_name: "opustime"
  send_grid_password: "projectZulu3nat3"
  
stage:
  SECRET_KEY_BASE: 'stage key here'

production:
  SECRET_KEY_BASE: "2041a74fcdc42ab1aa6798f541cacbe0cb41a206a996443d75b213387249d437d00eafff57a94cb43186d7b87aa45b5d8d4a3f34597dfc6452b57dd0a0eaf54c"
  XERO_KEY: 'CCZAECL5SX2OQSQD9TERR0RLGC5MYD'
  XERO_SECRET: 'ZMXHT53AKJAONQI6FFICMFBHVSPBBB'
  FB_KEY: '1104113702960985'    # Live
  FB_SECRET: '1b35846862052f07c551686a1c77841a' # Live
#  FB_KEY: '733316870157714'    # staging
#  FB_SECRET: 'b1553add37d0cb512f7b5ca0669c56fa' # staging
  ONLINE_FB_KEY: '1379043992119808' #live
  ONLINE_FB_SECRET: 'bf83dec4dd5e27075c2a97d3c93ed7e5' #live
#  CALENDAR_CLIENT_ID: '444748116899-m7hi657r7l9jq68qgbg9d9evft0cpbca.apps.googleusercontent.com'  #dhimananuj93@gmail.com
#  CALENDAR_SECRET_ID: 'laFEhH-0z7yF4-0LkRXOXuAC'
#  CALENDAR_ID: 'dhimananuj93@gmail.com'
  CALENDAR_CLIENT_ID: '982321280742-in60eh1a53cgknc3p8sv4f2cfmdkvngg.apps.googleusercontent.com'  #myopustime@gmail.com - poulin@260!
  CALENDAR_SECRET_ID: 'p1k1eAtRxpfefGSJ3R2MSzkc'
  CALENDAR_ID: 'myopustime@gmail.com'
  plivo_access_id: 'MAM2Y1NTE4ZJUWYTUXZT'
  plivo_secret_id: 'MzNjNTJlMTgwMWZiMWU2ODE4MzA5MWZiNjIwZTJk'
  elev_api_key: "57bcf30f63ed1"
  send_grid_user_name: "opustime"
  send_grid_password: "projectZulu3nat3"
  # Quickbooks Credentials
  #-------------------------------------------------#

  #-------------------------------------------------#
  # Authorized.net Credentials
  #-------------------------------------------------#

  #-------------------------------------------------#
