

# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
 # sidekiq -C config.yml
---
development:
  :pidfile: ./config/shared/pids/sidekiq.pid
  :logfile: ./config/shared/log/sidekiq.log
  :verbose: false
  :concurrency:  5
  :queues:
    - [often, 7]
    - [default, 5]
    - [seldom, 3]
    - mailer
    - mailers
    - qbo
    - subscription
    - admin
    - default

production:
  :pidfile: /home/ubuntu/opustime/shared/pids/sidekiq.pid
  :logfile: /home/ubuntu/opustime/shared/log/sidekiq.log
  :verbose: false
  :concurrency:  5
  :queues:
    - [often, 7]
    - [default, 5]
    - [seldom, 3]
    - mailer
    - mailers
    - qbo
    - subscription
    - admin
    - default

staging:
  :pidfile: ./config/shared/pids/sidekiq.pid
  :logfile: ./config/shared/log/sidekiq.log
  :verbose: false
  :concurrency:  5
  :queues:
    - [often, 7]
    - [default, 5]
    - [seldom, 3]
    - mailer
    - mailers
    - qbo
    - subscription
    - admin
    - default


:schedule:
  appnt_reminder:
    every: 1h   # Runs once per hour
    class: ReminderWorker